#pragma once
#define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS
#include <stdio.h>
#include <string>
#include <utility>
#include <vector>
#include <array>
#include <iostream>
#include <algorithm>
#include <fstream>
#include <functional>
#include <sstream>
#include <map>
#include <filesystem>
#include <any>
#include <unordered_map>
#include <regex>
#include <cctype>
#include <set>
#include <bitset>
#include <queue>
#include <unordered_set>
#include <memory>
#include <limits>
#include <thread>
#include <mutex>
#include <cstdarg>
#include <string_view>
#include <hash_map>
#include <hash_set>
#include <typeindex>
#include <string_view>
#include <assert.h>